device_target: CPU
ms_mode: 0
ms_amp_level: O0
keep_loss_fp32: true
ms_loss_scaler: static
ms_loss_scaler_value: 1024.0
overflow_still_update: false
clip_grad: false
ema: true
epochs: 5
per_batch_size: 1
img_size: 480
nbs: 64
accumulate: 4
log_interval: 50
data:
  dataset_name: fruit
  train_set: ./dataset/images/train
  val_set: ./dataset/images/val
  test_set: ./dataset/images/val
  nc: 17
  names:
  - Apple_healthy
  - Apple_rotten
  - Banana_healthy
  - Banana_rotten
  - Beans_healthy
  - Beans_rotten
  - Grape_healthy
  - Grape_rotten
  - Mango_healthy
  - Mango_rotten
  - Orange_healthy
  - Orange_rotten
  - Potato_healthy
  - Potato_rotten
  - Tomato_healthy
  - Tomato_rotten
  - non_produce
  num_parallel_workers: 0
  train_transforms:
  - func_name: letterbox
    scaleup: true
  - func_name: fliplr
    prob: 0.5
  - func_name: label_norm
    xyxy2xywh_: true
  - func_name: label_pad
    padding_size: 160
    padding_value: -1
  - func_name: image_norm
    scale: 255.0
  - func_name: image_transpose
    bgr2rgb: true
    hwc2chw: true
  test_transforms:
  - func_name: letterbox
    scaleup: false
    only_image: true
  - func_name: image_norm
    scale: 255.0
  - func_name: image_transpose
    bgr2rgb: true
    hwc2chw: true
optimizer:
  optimizer: momentum
  lr_init: 0.01
  momentum: 0.937
  nesterov: true
  loss_scale: 1.0
  warmup_epochs: 3
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  min_warmup_step: 100
  group_param: yolov8
  gp_weight_decay: 0.0005
  start_factor: 1.0
  end_factor: 0.01
loss:
  name: YOLOv8Loss
  box: 7.5
  cls: 0.5
  dfl: 1.5
  reg_max: 16
network:
  model_name: yolov8
  nc: 17
  reg_max: 16
  stride:
  - 8
  - 16
  - 32
  depth_multiple: 0.33
  width_multiple: 0.25
  max_channels: 1024
  backbone:
  - - -1
    - 1
    - ConvNormAct
    - - 64
      - 3
      - 2
  - - -1
    - 1
    - ConvNormAct
    - - 128
      - 3
      - 2
  - - -1
    - 3
    - C2f
    - - 128
      - true
  - - -1
    - 1
    - ConvNormAct
    - - 256
      - 3
      - 2
  - - -1
    - 6
    - C2f
    - - 256
      - true
  - - -1
    - 1
    - ConvNormAct
    - - 512
      - 3
      - 2
  - - -1
    - 6
    - C2f
    - - 512
      - true
  - - -1
    - 1
    - ConvNormAct
    - - 1024
      - 3
      - 2
  - - -1
    - 3
    - C2f
    - - 1024
      - true
  - - -1
    - 1
    - SPPF
    - - 1024
      - 5
  head:
  - - -1
    - 1
    - Upsample
    - - null
      - 2
      - nearest
  - - - -1
      - 6
    - 1
    - Concat
    - - 1
  - - -1
    - 3
    - C2f
    - - 512
  - - -1
    - 1
    - Upsample
    - - null
      - 2
      - nearest
  - - - -1
      - 4
    - 1
    - Concat
    - - 1
  - - -1
    - 3
    - C2f
    - - 256
  - - -1
    - 1
    - ConvNormAct
    - - 256
      - 3
      - 2
  - - - -1
      - 12
    - 1
    - Concat
    - - 1
  - - -1
    - 3
    - C2f
    - - 512
  - - -1
    - 1
    - ConvNormAct
    - - 512
      - 3
      - 2
  - - - -1
      - 9
    - 1
    - Concat
    - - 1
  - - -1
    - 3
    - C2f
    - - 1024
  - - - 15
      - 18
      - 21
    - 1
    - YOLOv8Head
    - - nc
      - reg_max
      - stride
